apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 20.8.0
    helm:
      releaseName: traefik
      parameters:
      - name: providers.kubernetesIngress.publishedService.enabled
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
