apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 3.1.3
    helm:
      releaseName: falco
      parameters:
      - name: falcosidekick.enabled
        value: "true"
      - name: falcosidekick.webui.enabled
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true