apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acorn-system
rules:
- apiGroups:
  - api.acorn.io
  - internal.acorn.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - pods/portforward
  - pods/ephemeralcontainers
  - configmaps
  - secrets
  - namespaces
  - services
  - serviceaccounts
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - roles
  - clusterrolebindings
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acorn-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acorn-system
subjects:
- kind: ServiceAccount
  name: acorn-system
  namespace: acorn-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acorn:cluster:view
rules:
- apiGroups:
  - api.acorn.io
  resources:
  - projects
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acorn:cluster:edit
rules:
- apiGroups:
  - api.acorn.io
  resources:
  - projects
  verbs:
  - get
  - list
- apiGroups:
  - api.acorn.io
  resources:
  - projects
  verbs:
  - create
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acorn:project:admin
rules:
- apiGroups:
  - api.acorn.io
  resources:
  - apps
  - acornimagebuilds
  - builders
  - images
  - volumes
  - containerreplicas
  - credentials
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.acorn.io
  resources:
  - images/details
  verbs:
  - get
- apiGroups:
  - api.acorn.io
  resources:
  - infos
  verbs:
  - list
- apiGroups:
  - api.acorn.io
  resources:
  - apps/log
  verbs:
  - get
- apiGroups:
  - api.acorn.io
  resources:
  - apps
  - images
  - credentials
  - secrets
  verbs:
  - create
  - update
  - delete
  - patch
- apiGroups:
  - api.acorn.io
  resources:
  - images/tag
  - apps/confirmupgrade
  verbs:
  - create
- apiGroups:
  - api.acorn.io
  resources:
  - volumes
  - containerreplicas
  verbs:
  - delete
- apiGroups:
  - api.acorn.io
  resources:
  - images/push
  - images/pull
  - containerreplicas/exec
  - secrets/reveal
  verbs:
  - get
- apiGroups:
  - api.acorn.io
  resources:
  - builders
  - acornimagebuilds
  verbs:
  - create
  - delete
- apiGroups:
  - api.acorn.io
  resources:
  - builders/port
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acorn:project:view
rules:
- apiGroups:
  - api.acorn.io
  resources:
  - apps
  - acornimagebuilds
  - builders
  - images
  - volumes
  - containerreplicas
  - credentials
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.acorn.io
  resources:
  - images/details
  verbs:
  - get
- apiGroups:
  - api.acorn.io
  resources:
  - infos
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acorn:project:view-logs
rules:
- apiGroups:
  - api.acorn.io
  resources:
  - apps/log
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acorn:project:edit
rules:
- apiGroups:
  - api.acorn.io
  resources:
  - apps
  - acornimagebuilds
  - builders
  - images
  - volumes
  - containerreplicas
  - credentials
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.acorn.io
  resources:
  - images/details
  verbs:
  - get
- apiGroups:
  - api.acorn.io
  resources:
  - infos
  verbs:
  - list
- apiGroups:
  - api.acorn.io
  resources:
  - apps/log
  verbs:
  - get
- apiGroups:
  - api.acorn.io
  resources:
  - apps
  - images
  - credentials
  - secrets
  verbs:
  - create
  - update
  - delete
  - patch
- apiGroups:
  - api.acorn.io
  resources:
  - images/tag
  - apps/confirmupgrade
  verbs:
  - create
- apiGroups:
  - api.acorn.io
  resources:
  - volumes
  - containerreplicas
  verbs:
  - delete
- apiGroups:
  - api.acorn.io
  resources:
  - images/push
  - images/pull
  - containerreplicas/exec
  - secrets/reveal
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acorn:project:build
rules:
- apiGroups:
  - api.acorn.io
  resources:
  - builders
  - acornimagebuilds
  verbs:
  - create
  - delete
- apiGroups:
  - api.acorn.io
  resources:
  - builders/port
  verbs:
  - get

---
apiVersion: v1
kind: Namespace
metadata:
  name: acorn-image-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: acorn-system

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    acorn.io/project: "true"
  name: acorn

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.api.acorn.io
spec:
  group: api.acorn.io
  groupPriorityMinimum: 2000
  insecureSkipTLSVerify: true
  service:
    name: acorn-api
    namespace: acorn-system
    port: 7443
  version: v1
  versionPriority: 10

---
apiVersion: v1
kind: Service
metadata:
  name: acorn-api
  namespace: acorn-system
spec:
  ports:
  - port: 7443
    protocol: TCP
    targetPort: 7443
  selector:
    app: acorn-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acorn-api
  namespace: acorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acorn-api
  template:
    metadata:
      labels:
        app: acorn-api
    spec:
      containers:
      - args:
        - api-server
        env:
        - name: ACORN_IMAGE
          value: ghcr.io/acorn-io/acorn:v0.5.1
        image: ghcr.io/acorn-io/acorn:v0.5.1
        name: acorn-api
        ports:
        - containerPort: 7443
        securityContext:
          runAsUser: 1000
      serviceAccountName: acorn-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acorn-system
  namespace: acorn-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acorn-controller
  namespace: acorn-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acorn-controller
  template:
    metadata:
      labels:
        app: acorn-controller
    spec:
      containers:
      - args:
        - controller
        env:
        - name: ACORN_IMAGE
          value: ghcr.io/acorn-io/acorn:v0.5.1
        image: ghcr.io/acorn-io/acorn:v0.5.1
        name: acorn-controller
        securityContext:
          runAsUser: 1000
      serviceAccountName: acorn-system

---
apiVersion: v1
data:
  config: '{"ingressClassName":null,"clusterDomains":null,"letsEncrypt":null,"letsEncryptEmail":"","letsEncryptTOSAgree":null,"setPodSecurityEnforceProfile":null,"podSecurityEnforceProfile":"","defaultPublishMode":"","httpEndpointPattern":null,"internalClusterDomain":"","acornDNS":null,"acornDNSEndpoint":null,"autoUpgradeInterval":null,"recordBuilds":null,"publishBuilders":null,"builderPerProject":null,"internalRegistryPrefix":null,"ignoreUserLabelsAndAnnotations":null,"allowUserLabels":[],"allowUserAnnotations":[],"workloadMemoryDefault":null,"workloadMemoryMaximum":null,"useCustomCABundle":false,"propagateProjectAnnotations":[],"propagateProjectLabels":[]}'
kind: ConfigMap
metadata:
  name: acorn-config
  namespace: acorn-system
