apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: elastic
    repoURL: registry-1.docker.io/lucj
    targetRevision: v1.0.0
    helm:
      releaseName: elastic
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true