apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollout
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.29.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
