apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lucj/k8sapps.git
    targetRevision: main
    path: descheduler
    plugin: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: descheduler
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
