repositories:
  - name: stakater
    url: https://stakater.github.io/stakater-charts


releases:
  - name: reloader
    namespace: reloader
    labels:
      app: reloader
    chart: stakater/reloader
    version: ~0.0.126