repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    labels:
      app: cert-manager
    chart: jetstack/cert-manager
    version: ~1.9.1
    values:
      - values.yaml

